app:
  name: acontext-api
  env: debug # available mode: debug / release / test
  host: 0.0.0.0
  port: ${API_EXPORT_PORT} # Bind to .env 8029

root:
  apiBearerToken: "${ROOT_API_BEARER_TOKEN}"
  secretPepper: "your-secret-pepper"

log:
  level: info # debug/info/warn/error

database:
  dsn: "host=${DATABASE_HOST} user=${DATABASE_USER} password=${DATABASE_PASSWORD} dbname=${DATABASE_NAME} port=${DATABASE_EXPORT_PORT} sslmode=disable TimeZone=UTC"
  maxOpen: 20
  maxIdle: 10
  autoMigrate: true

redis:
  addr: "${REDIS_HOST}:${REDIS_EXPORT_PORT}"
  password: "${REDIS_PASSWORD}"
  db: 0
  poolSize: 10

rabbitmq:
  url: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_EXPORT_PORT}/${RABBITMQ_VHOST_ENCODED}"
  prefetch: 10

s3:
  endpoint: "${S3_ENDPOINT}"
  region: "${S3_REGION}"
  accessKey: "${S3_ACCESS_KEY}"
  secretKey: "${S3_SECRET_KEY}"
  bucket: "${S3_BUCKET}"
  usePathStyle: true
  presignExpireSec: 900
  # sse: "aws:kms"
